### ISSUE TITLE
Things to do before Testing Round 3

### ISSUE THREAD

**Issue by Quantum158** [Vanilla-Redone/Walls#15]
- [x] Finish the jungle map (#12)
- [x] Finish checklist from internal testing R1 (#14)
- [x] Finish checklist from R1 (#13)
- [x] Create a mock-up map selector (#7)
- [x] Finish sound effects (#8)
- [x] Loot tables and chest gen
